"""Technical feature extraction engine for Trade Intelligence (Phase 2)."""

from trade_intelligence.features.exceptions import (
    CorruptedCandleError,
    CorruptedCandleValueError,
    DuplicateTimestampError,
    EmptySequenceError,
    FeatureError,
    FeatureValidationError,
    FormingCandleError,
    InvalidIntervalError,
    InvalidTimestampError,
    LookaheadViolationError,
    MalformedIntervalSpacingError,
    UnsortedSequenceError,
)
from trade_intelligence.features.types import (
    CandleSegment,
    FeatureCandle,
    FeatureMatrix,
    FeatureMetadata,
    FeatureSpec,
    MomentumSpec,
    NumericalCandleArrays,
    StructureSpec,
    TrendSpec,
    VolatilitySpec,
    VolumeSpec,
)
from trade_intelligence.features.validation import (
    convert_candles_to_arrays,
    partition_contiguous_segments,
    validate_candle,
    validate_candle_sequence,
)
from trade_intelligence.features.kernels import (
    calc_atr,
    calc_bollinger_bands,
    calc_ema,
    calc_ema_slope,
    calc_ema_spread,
    calc_macd,
    calc_natr,
    calc_price_ema_ratio,
    calc_roc,
    calc_rsi,
    calc_rvol,
    calc_taker_buy_share,
    calc_true_range,
    calc_volume_sma,
    compute_all_kernels,
    compute_momentum_features,
    compute_trend_features,
    compute_volatility_features,
    compute_volume_features,
)

__all__ = [
    # Types & Models
    "FeatureCandle",
    "NumericalCandleArrays",
    "CandleSegment",
    "FeatureSpec",
    "StructureSpec",
    "TrendSpec",
    "MomentumSpec",
    "VolatilitySpec",
    "VolumeSpec",
    "FeatureMetadata",
    "FeatureMatrix",
    # Exceptions
    "FeatureError",
    "FeatureValidationError",
    "EmptySequenceError",
    "UnsortedSequenceError",
    "DuplicateTimestampError",
    "MalformedIntervalSpacingError",
    "FormingCandleError",
    "CorruptedCandleError",
    "CorruptedCandleValueError",
    "InvalidIntervalError",
    "InvalidTimestampError",
    "LookaheadViolationError",
    # Validation & Boundary Conversion
    "validate_candle",
    "validate_candle_sequence",
    "convert_candles_to_arrays",
    "partition_contiguous_segments",
    # Kernels & Calculation
    "compute_all_kernels",
    "calc_ema",
    "calc_price_ema_ratio",
    "calc_ema_spread",
    "calc_ema_slope",
    "calc_rsi",
    "calc_macd",
    "calc_roc",
    "calc_true_range",
    "calc_atr",
    "calc_natr",
    "calc_bollinger_bands",
    "calc_volume_sma",
    "calc_rvol",
    "calc_taker_buy_share",
    "compute_trend_features",
    "compute_momentum_features",
    "compute_volatility_features",
    "compute_volume_features",
]
